# ══════════════════════════════════════════════════════════════
#  Big test — One-Click Setup (PowerShell)
#  Generated by Overlord Setup Agent
# ══════════════════════════════════════════════════════════════

Write-Host "  Setting up Big test..." -ForegroundColor Cyan

# Step 1: Create .env from template if it doesn't exist
if (-not (Test-Path ".env")) {
    if (Test-Path ".env.template") {
        Copy-Item ".env.template" ".env"
        Write-Host "  [OK] Created .env from template — fill in your values." -ForegroundColor Yellow
    }
} else {
    Write-Host "  [OK] .env already exists." -ForegroundColor Green
}

# Step 2: Install dependencies
Write-Host "  Installing dependencies..." -ForegroundColor Cyan
pip install -r requirements.txt
if ($LASTEXITCODE -ne 0) {
    Write-Host "  [FAIL] Dependency install failed." -ForegroundColor Red
    exit 1
}
Write-Host "  [OK] Dependencies installed." -ForegroundColor Green

# Step 3: Ready
Write-Host ""
Write-Host "  Setup complete! To start:" -ForegroundColor Green
Write-Host "    python app.py" -ForegroundColor White
Write-Host "  Or use Docker:" -ForegroundColor Green
Write-Host "    docker-compose up -d" -ForegroundColor White
Write-Host ""
